# Server settings
server:
    port: 8086

# SPRING PROFILES
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://172.20.8.242:3306/dudu_ops?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
    jpa:
      show-sql: true
      
# HTTP ENCODING
http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart.maxFileSize: 10Mb

#Redis
redis:
    host: 172.20.14.223
    port: 6379
    password: yytx!2018
    # 连接池中的最大空闲连接
    pool.max-idle: 10
    # 连接池中的最小空闲连接
    #pool.min-idle: 1
    # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 10
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: 20000
    # 连接超时时间（毫秒）
    timeout: 20000

# MyBatis
mybatis:
    mapper-locations: classpath:/mappings/*.xml
    type-aliases-package: yak.managerger
    configuration.mapUnderscoreToCamelCase: true
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count\=countSql

# LOGGING
logging:
    file: ../../logs/yak-manager.log
    level:
       yak.manager: INFO
